name: MoonMod
main: com.unkzdomain.bukkit.moonmod.MoonMod
version: "0.1-pre"
commands:
    /launch:
        description: Launch self to Moon or Earth.
        usage: /<command> <Moon|Earth>
        aliases: ['/l']
    /launchp:
        description: Launch player to Moon or Earth.
        usage: /<command> <player> <Moon|Earth>
        aliases: ['/lp']
